# Generated by Django 5.0.3 on 2024-12-06 18:10

import django.core.validators
import django.db.models.deletion
import seo.models
from django.db import migrations, models


def create_ghost_redirect(apps, schema_editor):
    GhostRedirects = apps.get_model("seo", "GhostRedirects")
    GhostRedirects.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0018_alter_metagenerationrule_type_seotagpage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GhostRedirects",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "редиректы",
                "verbose_name_plural": "редиректы",
            },
        ),
        migrations.CreateModel(
            name="Redirects",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "src",
                    seo.models.StandardURLField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_url",
                                message="Url дожен быть с доменом visota13.ru",
                                regex="^(http[s]?://)?(www\\.)?visota13\\.ru",
                            )
                        ],
                        verbose_name="откуда",
                    ),
                ),
                (
                    "to",
                    seo.models.StandardURLField(
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_url",
                                message="Url дожен быть с доменом visota13.ru",
                                regex="^(http[s]?://)?(www\\.)?visota13\\.ru",
                            )
                        ],
                        verbose_name="куда",
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=200)),
                ("destination", models.CharField(blank=True, max_length=200)),
                ("permanent", models.BooleanField(default=True, verbose_name="тип редиректа постоянный")),
                ("parent", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="seo.ghostredirects")),
            ],
            options={
                "verbose_name": "редирект",
                "verbose_name_plural": "редиректы",
            },
        ),
        migrations.RunPython(create_ghost_redirect, None),
    ]
