# Generated by Django 5.0.3 on 2024-12-14 15:29

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
import seo.models
from django.db import migrations, models


def create_ghost_redirect(apps, schema_editor):
    GhostRedirect = apps.get_model("seo", "GhostRedirect")
    GhostRedirect.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0019_ghostredirects_redirects"),
    ]

    operations = [
        migrations.CreateModel(
            name="GhostRedirect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "редиректы",
                "verbose_name_plural": "редиректы",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name="redirects",
            name="parent",
        ),
        migrations.CreateModel(
            name="GhostRedirectTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="seo.ghostredirect",
                    ),
                ),
            ],
            options={
                "verbose_name": "редиректы Translation",
                "db_table": "seo_ghostredirect_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Redirect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("parent", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="seo.ghostredirect")),
            ],
            options={
                "verbose_name": "редирект",
                "verbose_name_plural": "редиректы",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RedirectTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                (
                    "src",
                    seo.models.StandardURLField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_url",
                                message="Url дожен быть с доменом visota13.ru",
                                regex="^(http[s]?://)?(www\\.)?visota13\\.ru",
                            )
                        ],
                        verbose_name="откуда",
                    ),
                ),
                (
                    "to",
                    seo.models.StandardURLField(
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_url",
                                message="Url дожен быть с доменом visota13.ru",
                                regex="^(http[s]?://)?(www\\.)?visota13\\.ru",
                            )
                        ],
                        verbose_name="куда",
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=200)),
                ("destination", models.CharField(blank=True, max_length=200)),
                ("permanent", models.BooleanField(default=True, verbose_name="тип редиректа постоянный")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="seo.redirect",
                    ),
                ),
            ],
            options={
                "verbose_name": "редирект Translation",
                "db_table": "seo_redirect_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name="GhostRedirects",
        ),
        migrations.DeleteModel(
            name="Redirects",
        ),
        migrations.RunPython(create_ghost_redirect, None),
    ]
