# Generated by Django 5.0.3 on 2025-03-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0021_city_alter_metagenerationrule_type_citycategoryseo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='sitemap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='seo.sitemap'),
        ),
    ]
