# Generated by Django 5.0.3 on 2025-03-09 08:39


from django.db import migrations


def change_metagenerationrule_instruction(apps, schema_editor):
    MetaGenerationRule = apps.get_model("seo", "MetaGenerationRule")

    category_instruction = """Для генерации можно использовать переменные, название которых заключается в фигурные скобки {} (например, {name}).
                              Доступные переменные:
                              {name} - название категории"""
    category = MetaGenerationRule.objects.get(type="ctg")
    category.instruction = category_instruction
    category.save()

    product_instruction = """Для генерации можно использовать переменные, название которых заключается в фигурные скобки {} (например, {name}).
                             Доступные переменные:
                             {name} - название товара
                             {price} - цена"""
    product = MetaGenerationRule.objects.get(type="prd")
    product.instruction = product_instruction
    product.save()

    tag_instruction = """Для генерации можно использовать переменные, названия которых заключается в фигурные скобки {} (например, {name}).
                         Доступные переменные: 
                         {name} - название тега"""
    tag = MetaGenerationRule.objects.get(type="tag")
    tag.instruction = tag_instruction
    tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_remove_subcategorytranslation_description"),
        ("seo", "0022_city_sitemap"),
    ]

    operations = [
        migrations.RunPython(change_metagenerationrule_instruction, None),
    ]
