# Generated by Django 5.0.3 on 2024-12-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_offerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pricerequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='pricerequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='samplerequest',
            name='card',
        ),
        migrations.RemoveField(
            model_name='samplerequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='samplerequest',
            name='entity',
        ),
    ]
