# Generated by Django 5.0.3 on 2024-12-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_remove_consultationrequest_activity_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialOfferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='контактное лицо')),
                ('number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'запрос коммерческого предложения',
                'verbose_name_plural': 'запросы коммерческих предложений',
            },
        ),
        migrations.DeleteModel(
            name='OfferRequest',
        ),
    ]
