# Generated by Django 5.0.3 on 2024-12-07 09:26

import common.utils
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_remove_productcharacteristic_unique_product_characteristic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDoc",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docs",
                        to="products.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "документ товара",
                "verbose_name_plural": "документы товаров",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProductDocTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("file_name", models.CharField(max_length=100, verbose_name="название документа")),
                ("url", models.FileField(upload_to=common.utils.upload_product_file_to, verbose_name="документ")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="products.productdoc",
                    ),
                ),
            ],
            options={
                "verbose_name": "документ товара Translation",
                "db_table": "products_productdoc_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
