# Generated by Django 5.0.3 on 2025-02-10 09:33

import django_ckeditor_5.fields
from django.db import migrations


def set_my_defaults(apps, schema_editor):
    SubCategory = apps.get_model("products", "SubCategory")
    SubCategoryTranslation = apps.get_model("products", "SubCategoryTranslation")
    for cat in SubCategory.objects.all():
        translations = SubCategoryTranslation.objects.filter(master_id=cat.id)
        for translation in translations:
            translation.content = translation.name
            translation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_productdoc_productdoctranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategorytranslation",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name="описание категории"),
        ),
        migrations.RunPython(set_my_defaults, None),
        migrations.AlterField(
            model_name="subcategorytranslation",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="описание категории"),
        ),
    ]
