# Generated by Django 5.0.3 on 2025-03-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_subcategorytranslation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorytranslation',
            name='description',
            field=models.TextField(verbose_name='краткое описание'),
        ),
    ]
