# Generated by Django 5.0.3 on 2025-03-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_subcategorytranslation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorytranslation',
            name='description',
        ),
    ]
